baseURL = 'https://blog.hon-it.be/'
languageCode = 'en-GB'
title = 'HON-IT | Wireless Engineering'
theme = 'PaperMod'

[params]
    author = 'Nick Cuypers'
    description = 'CWNE Candidate - Wireless & Network Engineering Blog'
    ShowCodeCopyButtons = true
    mainSections = ['posts']